//Generate a number so that it can be used to repeat a certain amount of "i" or "o"
const randomLetterAmount = () => {
  let number = (Math.floor(Math.random() * 6));
  return number;
};

//Function that returns a random "bloop" variation
const bloopWord = () => {
  let letterToRepeat = "o";
  let number = randomLetterAmount();
  //If the number generated by the randomLetterAmount fucntion is 0 or 1, it will just return "bloop" as the minimum amount of o's needed is 2
  if (number === 0 || number === 1) {
    return "bloop";
  } else {
    return `bl${letterToRepeat.repeat(number)}p`;
  }
};

//Function that returns a random "blip" variation
const blipWord = () => {
  let letterToRepeat = "i";
  let number = randomLetterAmount();
  //If the random number generated by the randomLetterAmount function is 0, it will just return "blip" because there is no repeat of 0
  if (number === 0) {
    return "blip";
  } else {
    return `bl${letterToRepeat.repeat(number)}p`;
  }
};

//The functions are then put in an array so that a random blip or bloop can be chosen to make up a blip+bloop sentence
let wordFuncArr = [bloopWord, blipWord];

//This is a random number generator to be asscociated with which function to be chosen in the wordFuncArr
const randomFuncNum = () => {
  let number = (Math.floor(Math.random() * wordFuncArr.length));
  return number;
}

//Main function to turn the "string" into a sentence of corresponding blip's and bloop's
const textToFish = (string) => {
  //Splits the string into an array format
  stringArr = string.split(" ");

  //Maps the array and creates a corresponding blip or bloop
  let sentenceArr = stringArr.map(word => {
    return wordFuncArr[randomFuncNum()]();
  })

  //Join the mapped array into a string
  return sentenceArr.join(" ");
};